name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  main:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - 4.3

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          pull: true
          no-cache: true
          platforms: linux/amd64
          tags: emqx:${{ matrix.version }}
          file: ${{ matrix.version }}/Dockerfile
          context: ${{ matrix.version }}
      - name: Check image
        timeout-minutes: 1
        run: |
          docker run -d -p 8081:8081 --name emqx emqx:${{ matrix.version }}
          while !curl -fs 127.0.0.1:18083/status > /dev/null; do
            echo "waiting for emqx"
          done
          echo "================================================================"
          echo "emqx is running"
